# Generated by Django 5.0.6 on 2026-07-27 23:05

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Farmer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('phone_number', models.CharField(max_length=20)),
                ('community', models.CharField(help_text='Community or town the farmer operates in', max_length=120)),
                ('date_registered', models.DateField(default=django.utils.timezone.localdate)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Plot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plot_code', models.CharField(max_length=50, unique=True)),
                ('size_hectares', models.DecimalField(decimal_places=2, help_text='Plot size in hectares (must be positive)', max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('cocoa_variety', models.CharField(blank=True, max_length=100, null=True)),
                ('date_registered', models.DateField(default=django.utils.timezone.localdate)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plots', to='tracker.farmer')),
            ],
            options={
                'ordering': ['plot_code'],
            },
        ),
        migrations.CreateModel(
            name='HarvestRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('harvest_date', models.DateField()),
                ('weight_kg', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('quality_grade', models.CharField(choices=[('A', 'Grade A'), ('B', 'Grade B'), ('C', 'Grade C')], max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='harvests', to='tracker.plot')),
            ],
            options={
                'ordering': ['-harvest_date'],
            },
        ),
        migrations.AddConstraint(
            model_name='harvestrecord',
            constraint=models.CheckConstraint(check=models.Q(('weight_kg__gt', 0)), name='harvest_weight_positive'),
        ),
    ]
